---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: courie-web-canary-template
metadata:
  name: courie-web-canary-template
objects:
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    # Must be the same name as the VS from Courie Helm install.
    name: courie-web-routing-config
  spec:
    hosts:
    - "courie-web.${CLUSTER_APPS_BASE_URL}"
    gateways:
    - courie-web-gateway
    http:
    - route:
      - destination:
          host: courie-web
          subset: v1
        weight: 50
      - destination:
          host: courie-web
          subset: v2
        weight: 50

- kind: DestinationRule
  metadata:
    name: courie-web-dr
  spec:
    host: courie-web
    subsets:
    - name: v1
      labels:
        version: 1.0.0
    - name: v2
      labels:
        version: 2.0.0

parameters:
- description: The base app URL of your OpenShift Cluster. For example, apps.cluster.example.com
  displayName: App Cluster URL
  name: CLUSTER_APPS_BASE_URL
  required: true