---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: delivery-service-cb-template
metadata:
  name: delivery-service-cb-template
objects:
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: delivery-service-routing-config
  spec:
    hosts:
    - "delivery-api.${CLUSTER_APPS_BASE_URL}"
    gateways:
    - delivery-service-gateway
    trafficPolicy:
      outlierDetection:
        consecutiveErrors: 1
        interval: 10s
        baseEjectionTime: 1m
        maxEjectionPercent: 100
    http:
    - route:
      - destination:
          host: delivery-service
          subset: v1

parameters:
- description: The base app URL of your OpenShift Cluster. For example, apps.cluster.example.com
  displayName: App Cluster URL
  name: CLUSTER_APPS_BASE_URL
  required: true